SET( BIOCPP_EXAMPLE_SOURCES ${BIOCPP_EXAMPLE_SOURCES} PARENT_SCOPE )
SET( CGAL_LIBRARIES ${CGAL_LIBRARIES} PARENT_SCOPE )

project( delaunay_exposed )
set_property(
  SOURCE ${BIOCPP_EXAMPLE_SOURCES}/${PROJECT_NAME}.cpp
  PROPERTY COMPILE_DEFINITIONS BIOCPP_INCLUDE_PDB
  PROPERTY COMPILE_DEFINITIONS BIOCPP_INCLUDE_STANDARD
  PROPERTY COMPILE_DEFINITIONS BIOCPP_INCLUDE_CGAL
)
add_executable(${PROJECT_NAME} ${BIOCPP_EXAMPLE_SOURCES}/${PROJECT_NAME}.cpp)
target_link_libraries(${PROJECT_NAME} ${CGAL_LIBRARIES})
