SET( BIOCPP_EXAMPLE_SOURCES ${BIOCPP_EXAMPLE_SOURCES} PARENT_SCOPE )

project( fasta_align )
set_property(
  SOURCE ${BIOCPP_EXAMPLE_SOURCES}/${PROJECT_NAME}.cpp
  PROPERTY COMPILE_DEFINITIONS BIOCPP_INCLUDE_FASTA_ALIGNMENT
  PROPERTY COMPILE_DEFINITIONS BIOCPP_INCLUDE_FASTA_SUBST_MATRIX_BLOSUM62 
)
add_executable(${PROJECT_NAME} ${BIOCPP_EXAMPLE_SOURCES}/${PROJECT_NAME}.cpp)
