SET( BIOCPP_EXAMPLE_SOURCES ${BIOCPP_EXAMPLE_SOURCES} PARENT_SCOPE )

project( surface_area_lcpo )
set_property(
  SOURCE ${BIOCPP_EXAMPLE_SOURCES}/${PROJECT_NAME}.cpp
  PROPERTY COMPILE_DEFINITIONS BIOCPP_INCLUDE_PDB
  PROPERTY COMPILE_DEFINITIONS BIOCPP_INCLUDE_MORPHOLOGY
  PROPERTY COMPILE_DEFINITIONS BIOCPP_DONT_INCLUDE_CGAL
)
add_executable(${PROJECT_NAME} ${BIOCPP_EXAMPLE_SOURCES}/${PROJECT_NAME}.cpp)
